services:
  auth:
    # build: ./cmd/auth
    build:
      context: .
      dockerfile:
        cmd/auth/Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db

  # payments:
  #   build: ./cmd/payments
  #   depends_on:
  #     - db

  db:
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  db-setup:
    image: alpine:latest
    depends_on:
      - db
    restart: never

volumes:
  db-data:
    external: true