@AUTH_URL=http://localhost:4000/api/v1
@PAYMENTS_URL=http://localhost:4001/api/v1

POST {{AUTH_URL}}/register
Content-Type: application/json

{
    "firstName": "Susan",
    "lastName": "Briggs",
    "username": "SusieB",
    "email": "s.briggs@hotmail.com",
    "password": "abcdefg"
}

###

POST {{AUTH_URL}}/login
Content-Type: application/json

{
    "username": "SusieB",
    "password": "abcdefg"
}

###

POST {{PAYMENTS_URL}}/deposit
Content-Type: application/json

{
    "currencyTicker": "GBP",
    "amount": 500
}