CREATE TABLE IF NOT EXISTS deposits (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    account_id INTEGER NOT NULL REFERENCES accounts (id),
    currency_id INTEGER NOT NULL REFERENCES currencies (id),
    amount BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);